### ISSUE TITLE
项目是否还活跃？RN Demo启动报错。

### ISSUE THREAD

**Issue by Luomusha** [seerline/react-native-clchart-demo#1]
请问项目是否还活着？什么时候能完成RN的接入计划？
我用rn启动项目报错。

**Comment by Micjoyce** [comment]
RN的接入我建议使用webview直接内嵌入，之前在尝试使用GCanvas的时候，安卓还是有一些问题。
这个项目只有在ios是正常的。如果ios有报错可以把报错贴出来，我看看

**Comment by Micjoyce** [comment]
暂时先关闭，如有问题请再打开
